config/routes.rb
Growth::Engine.routes.draw do
  root to: 'stats#index'
  
  resources :stats, only: [:index, :show]
  resources :emails, only: [:new, :create]
end

app/controllers/growth/application_controller.rb
module Growth
  class ApplicationController < ActionController::Base
    http_basic_authenticate_with name: Growth.username, password: Growth.password unless Rails.env.test?

    protect_from_forgery with: :exception
  end
end

app/controllers/growth/emails_controller.rb
require 'csv'

require_dependency "growth/application_controller"

module Growth
  class EmailsController < ApplicationController
    def new
      render locals: {
          resources_ids: parse_resource_ids
      }
    end

    def create
      redirect_back(fallback_location: root_path, notice: 'You successfully sent emails')
    end

    private

    def parse_resource_ids
      params[:source_resource_ids].join.delete(' ').each_char.map(&:to_i)
    end

    def permitted_params
      params.permit(:from, :subject, :body, :resources_ids)
    end
  end
end

app/controllers/growth/stats_controller.rb
require 'csv'

require_dependency "growth/application_controller"
require_dependency "growth/transactions/generate_retention_report"

module Growth
  class StatsController < ApplicationController
    def index
      resources = Growth.models_to_measure.map(&:constantize)

      render :index, locals: {year: get_year, resources: resources}
    end

    def show
      resource = params[:id].camelize

      respond_to do |format|
        format.html do
          Growth::Transactions::GenerateRetentionReport.new.call(associations: params['association']) do |m|
            m.success do |result|
              render :show, locals: {resource: resource, report: result[:report]}
            end

            m.failure do |result|
              render :show, locals: {resource: resource, report: result[:report]}
            end
          end
        end

        format.csv do
          source_resources_count = params[:source_resources_count].to_i
          target_resources_count = params[:target_resources_count].to_i

          Growth::Transactions::GenerateRetentionReport.new.call(associations: params['association']) do |m|
            m.success do |result|
              stats = result[:report][:resources_stats].find do |stats|
                stats[:total_source_resources] == source_resources_count
                stats[:total_target_resources] == target_resources_count
              end

              resources = resource.constantize.find(stats[:total_source_resources_ids])

              send_data to_csv(resources), filename: "#{resource.pluralize}-#{Date.today}.csv"
            end

            m.failure do |result|
              raise 'failed to export csv'
            end
          end
        end
      end
    end

    private

    def get_year
      params[:year].present? ? params[:year].to_i : Date.current.year
    end

    def to_csv(resources)
      attributes = %w{email}

      CSV.generate(headers: true) do |csv|
        csv << attributes

        resources.each do |user|
          csv << attributes.map{ |attr| user.send(attr) }
        end
      end
    end
  end
end

app/helpers/growth/application_helper.rb
require "groupdate"

module Growth
  module ApplicationHelper
    def get_grouped_options(resources)
      resources.map do |model|
        [
            model,
            model.reflect_on_all_associations(:has_many).map do |reflection|
              name = reflection.name.to_s.singularize.camelize
              [name, "#{model}-#{name}"]
            end
        ]
      end
    end

    def counts(grouped_models)
      counts = {}
      grouped_models&.count&.each do |key, value|
        counts.has_key?(value) ? counts[value] += 1 : counts[value] = 1
      end

      counts
    end

    def group_resource_by_month(resource, year)
      from, to = Date.parse("#{year.to_i - 1}-12-01"), Date.parse("#{year}-12-31")
      grouped_resource_by_month = resource
                                      .unscoped
                                      .group_by_month(:created_at, range: from..to)
                                      .count

      map_grouped_resource(grouped_resource_by_month, 1.month)
    end

    def group_resource_by_year(resource, resources)
      from = Date.parse("#{years_since_first_resource(resources).first}-01-01")
      to = Date.parse("#{years_since_first_resource(resources).last}-12-31")

      grouped_resource_by_year = resource.unscoped.group_by_year(:created_at, range: from..to).count
      map_grouped_resource(grouped_resource_by_year, 1.year)
    end

    def growth_today(resource)
      resource.constantize.where(created_at: Time.current.beginning_of_day..Time.current.end_of_day).count
    end
    
    def growth_month(resource)
      resource.constantize.where(created_at: Date.current.beginning_of_month..Date.current.end_of_month).count
    end
    
    def growth_year_to_date(resource)
      resource.constantize.unscoped.where(created_at: Time.current.beginning_of_year..Time.current.end_of_year).count
    end

    def years_since_first_resource(resources)
      return @years if defined? @years

      mapped_resources = resources.map do |resource|
        resource.unscoped.order(:created_at).first
      end.compact.map(&:created_at).sort

      @years = mapped_resources.empty? ? [Date.current.year] : (mapped_resources.first.to_date.year..Date.current.year).to_a
    end
    
    def pluralize_constant(count = nil, constant)
      return constant.to_s.pluralize if count == nil
      return pluralize(count, constant.to_s)
    end
    
    private

    def percentage_to_string(percentage)
      return percentage if percentage == '-'
      return '0%' if percentage == 0
      percentage > 0 ? "+#{percentage}%" : "#{percentage}%"
    end

    def growth_css_class(growth)
      return '' if growth == 0 || growth == '-'
      growth > 0 ? 'increase' : 'decrease'
    end

    def map_grouped_resource(grouped_resource, interval)
      grouped_resource.each do |date, count|
        percentage = get_change_in_percentage(grouped_resource[date - interval].try(:fetch, :count), count)

        grouped_resource[date] = {
            count: count,
            growth: percentage_to_string(percentage),
            css: growth_css_class(percentage)
        }
      end
    end

    def get_change_in_percentage(previous_value, current_value)
      return 0 if previous_value == current_value
      return '-' if previous_value.nil? || previous_value == 0

      if current_value > previous_value
        increase = current_value - previous_value
        increase_in_percentage = (increase / previous_value.to_f) * 100
        
        increase_in_percentage.round(2)
      else
        decrease = previous_value - current_value
        decrease_in_percentage = (decrease / previous_value.to_f) * 100
        
        -decrease_in_percentage.round(2)
      end
    end
  end
end

app/views/growth/stats/_associations.html.erb
<h5 class="my-4">Associations</h5>

<%= form_tag '/growth/stats', method: :get, class: 'mb-5' do %>
	<div class="row">
		<div class="col-md-2">
    	<%= select_tag 'association-select', grouped_options_for_select(get_grouped_options(resources), nil, prompt: 'Select model'), class: "form-control" %>
		</div>
		<div class="col-md-1">
			<%= submit_tag("Submit", class: "btn btn-primary") %>
		</div>
	</div>
<% end %>

<%= render "report", report: report %>

app/views/growth/stats/_form.html.erb
<%= form_tag emails_path do %>
  <%= hidden_field_tag 'resources_ids[]', resources_ids %>
  <div class="modal-body">
    <div class="form-group">
      <label class="col-form-label w-100">
        From:
        <%= text_field_tag :from, nil, class: 'form-control' %>
      </label>
    </div>

    <div class="form-group">
      <label class="col-form-label w-100">
        Subject:
        <%= text_field_tag :subject, nil, class: 'form-control' %>
      </label>
    </div>

    <div class="form-group">
      <label class="col-form-label w-100">
        body:
        <%= text_area_tag :body, nil, class: 'form-control' %>
      </label>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= submit_tag 'Send emails', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/growth/stats/_growth.html.erb
<h5 class="my-4 blue-text">MoM Growth</h5>

<%= form_tag '/growth/stats', method: :get do %>
	<div class="row">
		<div class="col-md-2">
  		<%= select_tag 'year', options_for_select((2014..Date.current.year).to_a, year), class: "form-control" %>
		</div>
		<div class="col-md-1">
			<%= submit_tag("Submit", class: "btn btn-primary") %>
		</div>
	</div>
<% end %>

<div class="row mt-2">
	<div class="col-md-12">
		<table class="table table-bordered">
		  <tr>
		    <th></th>
		    <th>January</th>
		    <th>February</th>
		    <th>March</th>
		    <th>April</th>
		    <th>May</th>
		    <th>June</th>
		    <th>July</th>
		    <th>August</th>
		    <th>September</th>
		    <th>October</th>
		    <th>November</th>
		    <th>December</th>
		  </tr>
		  <% resources.each do |resource| %>
		    <tr>
		      <td><b><%= pluralize_constant(resource) %></b></td>
					
          <% group_resource_by_month(resource, year).each do |date, stats| %>
            <% if date.year == year %>
              <td>
                <p><%= stats[:count] %></p>
                <p class="<%= stats[:css] %>"><%= stats[:growth] %></p>
              </td>
            <% end %>
          <% end %>
		    </tr>
		  <% end %>
		</table>
	</div>
</div>

<h5 class="my-4 blue-text">YoY Growth</h5>

<div class="row mt-2">
  <div class="col-md-12">
    <table class="table table-bordered">
      <tr>
        <th></th>
        <% years_since_first_resource(resources).each do |year| %>
          <th><%= year %></th>
        <% end %>
      </tr>
      <% resources.each do |resource| %>
        <tr>
          <td><b><%= pluralize_constant(resource) %></b></td>

          <% group_resource_by_year(resource, resources).each do |date, stats| %>
            <td>
              <p><%= stats[:count] %></p>
              <p class="<%= stats[:css] %>"><%= stats[:growth] %></p>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/growth/stats/_navbar.html.erb
<div class="sidebar-sticky">
	<ul class="nav flex-column">
		<li class="nav-link">
			<h1><%= link_to "GROWTH", root_path, class: 'logo' %></h1>
		</li>
    <% resources.each do |resource| %>
      <li class="nav-item">
				<%= link_to resource.to_s.pluralize, stat_path(resource.to_s.camelize(:lower)), class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
</div>

app/views/growth/stats/_report.html.erb
<% if report[:resources_stats].any? %>
  <div class="mt-2">
    <p><%= pluralize_constant(report[:source_resource]).capitalize %> that have <%= pluralize_constant(report[:target_resource]) %>: <%= report[:total_associated_resources] %></p>
    <p>Total <%= pluralize_constant(report[:target_resource]) %> created: <%= report[:total_target_resources] %></p>

    <%= form_tag new_email_path, remote: true, method: :get do %>

      <%= submit_tag 'Write email' %>

      <% report[:resources_stats].each do |stats| %>
        <p>
          <label>
            <%= check_box_tag 'source_resource_ids[]', stats[:total_source_resources_ids] %>
            <b>
              <%= stats[:total_source_resources] %> <%= pluralize_constant(report[:source_resource]) %></b> have <b><%= pluralize(stats[:total_target_resources], report[:target_resource].to_s.downcase) %> (<%= stats[:total_source_resources_percentage] %>% of <%= pluralize_constant(report[:source_resource]).capitalize %>)
            </b>
          </label>
          <% if report[:source_resource].has_attribute? :email %>
            <%= link_to 'export emails to csv', stat_path(report[:source_resource],
                                                          format: 'csv',
                                                          association: "#{report[:source_resource]}-#{report[:target_resource]}",
                                                          source_resources_count: stats[:total_source_resources],
                                                          target_resources_count: stats[:total_target_resources]),
                        class: 'ml-3'
            %>
          <% end %>
        </p>
      <% end %>

    <% end %>
  </div>
<% end %>

app/views/growth/stats/_sidebar.html.erb
<div class="sidebar-sticky">
	<ul class="nav flex-column">
		<li class="nav-link">
			<%= link_to root_path do %>
			  <h3 class="logo"><b>Growth</b>Engine</h3>
			<% end %>
		</li>
    <% resources.each do |resource| %>
      <li class="nav-item">
				<%= link_to resource.to_s.pluralize, stat_path(resource.to_s.camelize(:lower)), class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
</div>

app/views/growth/stats/_totals.html.erb
<h5 class="my-4 blue-text">Totals</h5>

<div class="row">
  <% resources.each do |resource| %>
		<div class="col-md-2">
			<div class="box">
				<p><%= pluralize_constant(resource) %></p>
				<h4><%= number_with_delimiter(resource.count, delimiter: ",") %></h4>
			</div>
		</div>
	<% end %>
</div>

app/views/growth/stats/index.html.erb
<%= render "totals", resources: resources %>
<%= render "growth", resources: resources, year: year %>

app/views/growth/stats/show.html.erb
<h4 class="my-4"><%= resource.pluralize %></h4>

<div class="row">
	<div class="col-md-2">
		<div class="box">
			<h6>Today</h6>
			<h2><%= number_with_delimiter(growth_today(resource), delimiter: ",") %></h2>
		</div>
	</div>
	<div class="col-md-2">
		<div class="box">
			<h6>This Month</h6>
			<h2><%= number_with_delimiter(growth_month(resource), delimiter: ",") %></h2>
		</div>
	</div>
	<div class="col-md-2">
		<div class="box">
			<h6>Year to date</h6>
			<h2><%= number_with_delimiter(growth_year_to_date(resource), delimiter: ",") %></h2>
		</div>
	</div>
</div>

<h4 class="my-4">Associations</h4>

<%= flash_message %>

<div class="row">
	<div class="col-md-12">
    <% resource.constantize.reflect_on_all_associations(:has_many).map do |reflection| %>
     	<span class="mr-3">
				<%= link_to reflection.name.to_s.singularize.camelize, stat_path(resource, association: "#{resource}-#{reflection.name.to_s.singularize.camelize}"), class: 'child-resource' %>
			</span>
		<% end %>
	
		<%= render "report", report: report %>
	</div>
</div>

<div class="modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="form-container">
      </div>
    </div>
  </div>
</div>

app/views/layouts/growth/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Growth</title>
  <%= stylesheet_link_tag "growth/application", media: "all" %>
  <%= javascript_include_tag "growth/application" %>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	
  <%= csrf_meta_tags %>
</head>
<body class="growth">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2 d-none d-md-block bg-blue sidebar px-0">
				<%= render "sidebar", resources: Growth.models_to_measure %>
			</div>
			<div class="col-md-10 pl-3">
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>